### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by fabioebner** [gdboling/spring-boot-multi-tenant-example#1]
Hi, i`m following or sample, but the spring-boot dont find the schema, I log in post and I got this problem:

LOG:  execute <unnamed>: SELECT 1
LOG:  execute <unnamed>: SET SEARCH_PATH TO teste1
LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY
LOG:  execute <unnamed>: BEGIN
ERROR:  relation "tb_usuario" does not exist at character 91
STATEMENT:  select user0_.id as id1_0_0_, user0_.nome as nome2_0_0_, user0_.senha as senha3_0_0_ from tb_usuario user0_ where user0_.id=$1
LOG:  execute S_2: ROLLBACK
LOG:  execute <unnamed>: SET SESSION CHARACTERISTICS AS TRANSACTION READ WRITE

in postman I pass the teste1 schema, and I have this schema and this table in that schema.. 

I`m using springboot 1.5.2

can U help me? tks

**Comment by kuonglv** [comment]
@fabioebner : I actually have not test this code, I'm interested in SaaS project in Spring boot and I cloned this project from github to study.
It looks like tables are not created, can you please try to create a table named as tb_usuario with following columns: id, nome, senha

**Comment by fabioebner** [comment]
@kuonglv I fixed my issue, I need to remove the dev-tools dependency to works..

**Comment by 3gcodes** [comment]
Sorry for the late reply. Are either of you still having an issue or can this be closed?

**Comment by fabioebner** [comment]
@gdboling U can close, but you know why if I put the dev-tools dep? dont works? tks

**Comment by 3gcodes** [comment]
I don't know. I can look into that. I'll create a new issue related.
